export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_FAILED = "GET_ALL_TASKS_FAILED";

export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const ADD_NEW_TASK_SUCCESS = "ADD_NEW_TASK_SUCCESS";
export const ADD_NEW_TASK_FAILED = "ADD_NEW_TASK_FAILED";

export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";
export const UPDATE_TASK_STATUS_SUCCESS = "UPDATE_TASK_STATUS_SUCCESS";
export const UPDATE_TASK_STATUS_FAILED = "UPDATE_TASK_STATUS_FAILED";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const TOGGLE_SELECT_ALL_BUTTON = "TOGGLE_SELECT_ALL_BUTTON";

export const UPDATE_ALL_ITEMS = "UPDATE_ALL_ITEMS"
export const UPDATE_ALL_ITEMS_SUCCESS = "UPDATE_ALL_ITEMS_SUCCESS"
export const UPDATE_ALL_ITEMS_FAILED = "UPDATE_ALL_ITEMS_FAILED"